### ISSUE TITLE
Add Natspec in combined_json

### ISSUE THREAD

**Issue by montyly** [vyperlang/vyper#1863]
Hi,

Would it be possible to add the natspec documentation to the combined json output?

Typically on the following:
```python
@public
def test(a: uint256) -> bool:
    """
    @author montyly
    @notice Nothing
    @dev This is a test
    @param a just a param
    @return always true
    """
    return True
```
It would be great if `vyper test.vy -f combined_json` could return the natspec to the json. Solidity output it as two dicts: https://solidity.readthedocs.io/en/latest/natspec-format.html#documentation-output.

This will help third-parties tools integration (such as https://github.com/crytic/crytic-compile/pull/66).

Thanks

**Comment by fubuloubu** [comment]
Yes! Should be possible. I don't think we actually parse the natspec currently, but it should be easy for someone to build a parser for the docstrings of a method and output the results alongside the other output formats.

**Comment by montyly** [comment]
# Task Description
- Write a parser for natspec
- Parse docstrings comments inside methods as natspec
- Add natspec comments to output from compiler

#  Acceptance criteria
- Extensive unit tests for parser
- Unit tests for vyper-cli and vyper-json
- Demonstrate compatibility with Solidity

# Required skills
- Python 3.6-3.8
- Familiarity with natspec
- Familiarity with Solidity

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 200.0 DAI (200.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/vyperlang/vyper/1863/4092).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/vyperlang/vyper/1863/4092).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $79,579.38 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 1 month from now.
Please review their action plans below:


**1) [nanspro](https://gitcoin.co/nanspro) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?mutate_worker_action=approve&worker=nanspro) | [reject worker](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?mutate_worker_action=reject&worker=nanspro))_.**

Crawl through file and produce the output in json by looking for natspec format keyowords, seems to be the way on first look. Did something similar with plasma-group's vyper code once

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/vyperlang/vyper/1863/4092).

**Comment by 1toya999** [comment]
> Hi,
> 
> Would it be possible to add the natspec documentation to the combined json output?
> 
> Typically on the following:
> 
> ```python
> @public
> def test(a: uint256) -> bool:
>     """
>     @author montyly
>     @notice Nothing
>     @dev This is a test
>     @param a just a param
>     @return always true
>     """
>     return True
> ```
> 
> It would be great if `vyper test.vy -f combined_json` could return the natspec to the json. Solidity output it as two dicts: https://solidity.readthedocs.io/en/latest/natspec-format.html#documentation-output.
> 
> This will help third-parties tools integration (such as [crytic/crytic-compile#66](https://github.com/crytic/crytic-compile/pull/66)).
> 
> Thanks

**Comment by nanspro** [comment]
I think this is reserved for @iamdefinitelyahuman so stopping work on this

**Comment by acheron2302** [comment]
This is not a pr or something like that but i have wrote a natspec conversion but it is still very ugly and i haven't write a test case but it work most of the time: https://github.com/acheron2302/vyper-doc. Sorry if it didn't work as you expect because this was just a fun challenge project for me at that time so i didn't put much effort into it

**Comment by fubuloubu** [comment]
@acheron2302 thanks for sharing!

**Comment by gitcoinbot** [comment]
@iamdefinitelyahuman Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=1) | [3 days](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=3) | [5 days](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=5) | [10 days](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=10) | [100 days](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=100)

**Comment by iamdefinitelyahuman** [comment]
@gitcoinbot Yes, I'm on it.

**Comment by gitcoinbot** [comment]
@iamdefinitelyahuman Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=1) | [3 days](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=3) | [5 days](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=5) | [10 days](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=10) | [100 days](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=100)

**Comment by gitcoinbot** [comment]
@iamdefinitelyahuman Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=1) | [3 days](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=3) | [5 days](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=5) | [10 days](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=10) | [100 days](https://gitcoin.co/issue/vyperlang/vyper/1863/4092?snooze=100)

**Comment by iamdefinitelyahuman** [comment]
@gitcoinbot yep i'm on it.

**Comment by montyly** [comment]
Thanks @iamdefinitelyahuman !

@ceresstation, can you validate the bounty? thx

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 200.0 DAI (200.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@iamdefinitelyahuman](https://gitcoin.co/iamdefinitelyahuman)



@ceresstation please take a look at the submitted work:
* [PR](https://github.com/vyperlang/vyper/pull/1899) by @iamdefinitelyahuman

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/vyperlang/vyper/1863/4092)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/vyperlang/vyper/1863/4092).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $81,163.16 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by iamdefinitelyahuman** [comment]
@montyly @ceresstation I just received an email that this bounty expires in two days, and the payment hasn't been released yet. Mind releasing it to me soon? Thanks.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 200.0 DAI (200.0 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @iamdefinitelyahuman.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/vyperlang/vyper/1863/4092)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $83,254.20 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
