### ISSUE TITLE
Meeting November 01 2021

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2492]
Start time: 19:00 UTC (https://time.is/UTC)

Vidchat link: https://meet.jit.si/VyperPlanningMeeting

Agenda:

- [x] https://github.com/vyperlang/vyper/issues/1363 I think we are ready for this. Just thread lark through codebase?
- [x] https://github.com/vyperlang/vyper/issues/2507
- [x] context/clarity on https://github.com/vyperlang/vyper/issues/2276
- [x] https://github.com/vyperlang/vyper/issues/1411 is this done?
- [x] https://github.com/vyperlang/vyper/issues/1656 is this still an issue?
- [x] https://github.com/vyperlang/vyper/issues/1618 is this done?
- [x] https://github.com/vyperlang/vyper/issues/982 is this still on the roadmap?
- [x] https://github.com/vyperlang/vyper/issues/2504
- [x] storage layout input

**Comment by fubuloubu** [comment]
next: #2519
