### ISSUE TITLE
checklist for v0.3.2

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#2700]
- [x] fix all dynarray tests
- [x] add slice tests (helps validate the changes to `copy_bytes`)
- [x] check conversions between all new types
- [x] add more edge case tests for new conversion rules
- [x] check functionality on all new types, including literals
- [ ] check bounds for all new types
- [x] ensure codesize regression for large arrays is fixed (https://github.com/vyperlang/vyper/issues/2656)

**Comment by fubuloubu** [comment]
convert to milestone w/ issues linked
