### ISSUE TITLE
meta: 0.4.0 checklist

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#3767]
meta issue to keep track of 0.4.0 issues

features:
- [x] library modules https://github.com/vyperlang/vyper/issues/2431
- [x] stateful modules https://github.com/vyperlang/vyper/issues/3722
  - [x] improve initializer list hint https://github.com/vyperlang/vyper/pull/3831
- [x] `.vyi` files https://github.com/vyperlang/vyper/issues/2814
- [x] `vyper.interfaces` -> `ethereum.ercs` https://github.com/vyperlang/vyper/issues/3675
  - [x] add warning/more helpful error message for usages of `vyper.interfaces`
  - [x] #3796
- [x] remove named reentrancy locks https://github.com/vyperlang/vyper/issues/3760
- [x] allow `convert()` to shorten bytestrings https://github.com/vyperlang/vyper/pull/3832
- [x] new `await` (or `call`) syntax for external calls https://github.com/vyperlang/vyper/issues/2856
- [x] floordiv operator https://github.com/vyperlang/vyper/issues/2847
- [ ] ban use of raw `self` (use `self.address`!), OR make interfaces interchangeable with `address` https://github.com/vyperlang/vyper/issues/3701#issuecomment-1880133880
- [ ] fix bytestring length inference
  - [ ] (related:) make bytestrings use ellipsis in all interfaces
- [x] update struct constructor syntax -- use kwargs instead of dict https://github.com/vyperlang/vyper/issues/2381#issuecomment-882801070
- [x] rename `enum` to `flag` https://github.com/vyperlang/vyper/issues/3642
- [x] change ABI for decimals https://github.com/vyperlang/vyper/pull/3696
- [x] auto-export events which are logged in a contract https://github.com/vyperlang/vyper/pull/2852#issuecomment-1128115146
- [x] create_from_blueprint default offset https://github.com/vyperlang/vyper/pull/3454
- [ ] add length inference to dynarrays
- [x] add `exports:` functionality https://github.com/vyperlang/vyper/pull/3786
- [x] export bundles https://github.com/vyperlang/vyper/pull/3698 -- DEFERRED TO 0.4.1

bugfixes: analysis
- [x] fix purity analysis of exprs (ex. https://github.com/vyperlang/vyper/issues/3161)
- [x] fix analysis of iterators https://github.com/vyperlang/vyper/pull/3764
- [x] implements mutability bug https://github.com/vyperlang/vyper/issues/3774

bugfixes: codegen
- [x] concat buffer overflow https://github.com/vyperlang/vyper/issues/3737
- [x] signed array indexes https://github.com/vyperlang/vyper/issues/3762
- [x] slice bounds check https://github.com/vyperlang/vyper/issues/3756

integration (compiler output):
- [ ] add `__init__()` to source map DEFERRED
- [ ] fix storage slot layout for large slots (use strings, ints get truncated)
- [ ] refactor storage layout https://github.com/vyperlang/vyper/pull/3789
- [ ] https://github.com/vyperlang/vyper/pull/3891

internal API:
- [ ] protect all CompilerData methods with anchor_evm_version

**Comment by ControlCplusControlV** [comment]
Could we maybe squeeze in #3607

**Comment by charles-cooper** [comment]
> Could we maybe squeeze in #3607

hm yea, need to think more on this, it's weird to have different default semantics for different functions

**Comment by ControlCplusControlV** [comment]
payable on everything and throw in non-payable? If not we can continue discussion elsewhere

**Comment by charles-cooper** [comment]
> payable on everything and throw in non-payable? If not we can continue discussion elsewhere

yep, please continue discussion on the issue itself

**Comment by mozz30-tech** [comment]
> meta issue to keep track of 0.4.0 issues
> 
> features:
> - [x] library modules https://github.com/vyperlang/vyper/issues/2431
> - [x] stateful modules https://github.com/vyperlang/vyper/issues/3722
>   - [x] improve initializer list hint https://github.com/vyperlang/vyper/pull/3831
> - [x] `.vyi` files https://github.com/vyperlang/vyper/issues/2814
> - [x] `vyper.interfaces` -> `ethereum.ercs` https://github.com/vyperlang/vyper/issues/3675
>   - [x] add warning/more helpful error message for usages of `vyper.interfaces`
>   - [x] #3796
> - [x] remove named reentrancy locks https://github.com/vyperlang/vyper/issues/3760
> - [x] allow `convert()` to shorten bytestrings https://github.com/vyperlang/vyper/pull/3832
> - [x] new `await` (or `call`) syntax for external calls https://github.com/vyperlang/vyper/issues/2856
> - [x] floordiv operator https://github.com/vyperlang/vyper/issues/2847
> - [ ] ban use of raw `self` (use `self.address`!), OR make interfaces interchangeable with `address` https://github.com/vyperlang/vyper/issues/3701#issuecomment-1880133880
> - [ ] fix bytestring length inference
>   - [ ] (related:) make bytestrings use ellipsis in all interfaces
> - [x] update struct constructor syntax -- use kwargs instead of dict https://github.com/vyperlang/vyper/issues/2381#issuecomment-882801070
> - [x] rename `enum` to `flag` https://github.com/vyperlang/vyper/issues/3642
> - [x] change ABI for decimals https://github.com/vyperlang/vyper/pull/3696
> - [x] auto-export events which are logged in a contract https://github.com/vyperlang/vyper/pull/2852#issuecomment-1128115146
> - [x] create_from_blueprint default offset https://github.com/vyperlang/vyper/pull/3454
> - [ ] add length inference to dynarrays
> - [x] add `exports:` functionality https://github.com/vyperlang/vyper/pull/3786
> - [x] export bundles https://github.com/vyperlang/vyper/pull/3698 -- DEFERRED TO 0.4.1
> 
> bugfixes: analysis
> - [x] fix purity analysis of exprs (ex. https://github.com/vyperlang/vyper/issues/3161)
> - [x] fix analysis of iterators https://github.com/vyperlang/vyper/pull/3764
> - [x] implements mutability bug https://github.com/vyperlang/vyper/issues/3774
> 
> bugfixes: codegen
> - [x] concat buffer overflow https://github.com/vyperlang/vyper/issues/3737
> - [x] signed array indexes https://github.com/vyperlang/vyper/issues/3762
> - [x] slice bounds check https://github.com/vyperlang/vyper/issues/3756
> 
> integration (compiler output):
> - [ ] add `__init__()` to source map DEFERRED
> - [ ] fix storage slot layout for large slots (use strings, ints get truncated)
> - [ ] refactor storage layout https://github.com/vyperlang/vyper/pull/3789
> - [ ] https://github.com/vyperlang/vyper/pull/3891
> 
> internal API:
> - [ ] protect all CompilerData methods with anchor_evm_version

**Comment by charles-cooper** [comment]
closing as finished with the [0.4.0 release](https://github.com/vyperlang/vyper/releases/tag/v0.4.0)
